// Generated by CoffeeScript 1.6.3
(function() {
    var e, t, n, r, i = function(e, t) {
        return function() {
            return e.apply(t, arguments);
        };
    };
    e = jQuery;
    t = function() {
        function e(e) {
            this.collapseHeader = i(this.collapseHeader, this);
            this.$el = e;
        }
        e.prototype.collapseHeader = function(e) {
            var t;
            t = this.$el.outerHeight();
            e > t ? this.$el.addClass("collapse") : this.$el.removeClass("collapse");
        };
        return e;
    }();
    n = function() {
        function e(e) {
            this.$el = e;
        }
        e.prototype.activateNav = function() {
            if (!this.$el.hasClass("active")) return this.$el.addClass("active");
        };
        e.prototype.deactivateNav = function() {
            if (this.$el.hasClass("active")) return this.$el.removeClass("active");
        };
        return e;
    }();
    r = function() {
        var t, n;
        t = e("#header");
        n = t.outerHeight();
        return e("#pageContent").css("padding-top", n);
    };
    e(function() {
        var i, s;
        i = new t(e("#header"));
        s = new n(e("#mobileNav"));
        e("#mobileNavButton").click(function(e) {
            e.stopPropagation();
            e.preventDefault();
            s.activateNav();
        });
        e("#pageWrapper").click(function(e) {
            e.stopPropagation();
            s.deactivateNav();
        });
        e(window).scroll(function() {
            return i.collapseHeader(e(window).scrollTop());
        });
        r();
        return e(window).resize(function() {
            return r();
        });
    });
}).call(this);